services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tldraw:latest
    container_name: tldraw
    restart: always
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - '3002:80'
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tldraw_cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
